import os

DATABASE_URL = os.getenv("DATABASE_URL")
REDIS_URL = os.getenv("REDIS_URL")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")

# TOTP 配置
TOTP_ISSUER = "TOTP_demo"
TOTP_DIGITS = 6
TOTP_INTERVAL = 30

# JWT 配置
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7
